syntax = "proto3";

package user;

service UsersService {
  rpc Register(RegisterRequest) returns (RegisterResponse) {}
  rpc VerifyEmail(VerifyEmailRequest) returns (VerifyEmailResponse) {}
  rpc Login(LoginRequest) returns (LoginResponse) {}
  rpc CurrentUser(CurrentUserRequest) returns (CurrentUserResponse) {}
  rpc RefreshToken(RefreshTokenRequest) returns (RefreshTokenResponse) {}
}

message CropData {
  int32 x = 1;
  int32 y = 2;
  int32 width = 3;
  int32 height = 4;
}

message RegisterRequest {
  string name = 1;
  string email = 2;
  string password = 3;
  int32 age = 4;
  string gender = 5;
  string country = 6;
  optional string temp_object_key = 7;
  optional CropData crop = 8;
}

message RegisterResponse {
  string id = 1;
  string message = 2;
}

message VerifyEmailRequest {
  string email = 1;
  int32 code = 2;
}

message VerifyEmailResponse {
  string message = 1;
}

message LoginRequest {
  string email = 1;
  string password = 2;
}

message LoginResponse {
  string access_token = 1;
  string refresh_token = 2;
}

message CurrentUserRequest {
  string id = 1;
}

message CurrentUserResponse {
  string id = 1;
  string name = 2;
  string email = 3;
  string avatar_key = 4;
  string gender = 5;
  string country = 6;
  int32 age = 7;
}

message RefreshTokenRequest {
  string refresh_token = 1;
}

message RefreshTokenResponse {
  string message = 1;
  string access_token = 2;
  string refresh_token = 3;
}