syntax = "proto3";

package user;

service UsersService {
  rpc Register(RegisterRequest) returns (RegisterResponse) {}
  rpc VerifyEmail(VerifyEmailRequest) returns (VerifyEmailResponse) {}
}

message RegisterRequest {
  string name = 1;
  string email = 2;
  string password = 3;
  string country = 4;
  int32 age = 5;
  string gender = 6;
}

message RegisterResponse {
  string id = 1;
  string message = 2;
}

message VerifyEmailRequest {
  string email = 1;
  int32 code = 2;
}

message VerifyEmailResponse {
  string message = 1;
}
